#!/bin/sh
set -e

echo '+cargo test --release --all'
cargo test --release --all

echo '+cargo clippy --release --all -- -D warnings'
BUILD_DUMMY_WASM_BINARY=1 cargo clippy --release --all -- -D warnings