// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for proposals_codex
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-06-27, STEPS: `1`, REPEAT: 1, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/joystream-node
// benchmark
// pallet
// --pallet=proposals_codex
// --extrinsic=*
// --chain=dev
// --steps=1
// --repeat=1
// --execution=wasm
// --no-verify
// --template=./scripts/../devops/joystream-pallet-weight-template.hbs
// --output=.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for proposals_codex.
pub trait WeightInfo {
	fn create_proposal_signal(i: u32, t: u32, d: u32, ) -> Weight;
	fn create_proposal_runtime_upgrade(i: u32, t: u32, d: u32, ) -> Weight;
	fn create_proposal_funding_request(i: u32, t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_max_validator_count(t: u32, d: u32, ) -> Weight;
	fn create_proposal_veto_proposal(t: u32, d: u32, ) -> Weight;
	fn create_proposal_create_working_group_lead_opening(i: u32, t: u32, d: u32, ) -> Weight;
	fn create_proposal_fill_working_group_lead_opening(t: u32, d: u32, ) -> Weight;
	fn create_proposal_update_working_group_budget(t: u32, d: u32, ) -> Weight;
	fn create_proposal_decrease_working_group_lead_stake(t: u32, d: u32, ) -> Weight;
	fn create_proposal_slash_working_group_lead(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_working_group_lead_reward(t: u32, d: u32, ) -> Weight;
	fn create_proposal_terminate_working_group_lead(t: u32, d: u32, ) -> Weight;
	fn create_proposal_amend_constitution(i: u32, t: u32, d: u32, ) -> Weight;
	fn create_proposal_cancel_working_group_lead_opening(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_membership_price(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_council_budget_increment(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_councilor_reward(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_initial_invitation_balance(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_initial_invitation_count(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_membership_lead_invitation_quota(t: u32, d: u32, ) -> Weight;
	fn create_proposal_set_referral_cut(t: u32, d: u32, ) -> Weight;
	fn create_proposal_create_blog_post(t: u32, d: u32, h: u32, b: u32, ) -> Weight;
	fn create_proposal_edit_blog_post(t: u32, d: u32, h: u32, b: u32, ) -> Weight;
	fn create_proposal_lock_blog_post(t: u32, d: u32, ) -> Weight;
	fn create_proposal_unlock_blog_post(t: u32, d: u32, ) -> Weight;
	fn create_proposal_update_global_nft_limit(t: u32, d: u32, ) -> Weight;
	fn create_proposal_update_channel_payouts(i: u32, t: u32, d: u32, ) -> Weight;
}

/// Weights for proposals_codex using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_signal(i: u32, t: u32, d: u32, ) -> Weight {
		(55_544_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(i as Weight))
			// Standard Error: 218_000
			.saturating_add((120_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 2_000
			.saturating_add((2_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_runtime_upgrade(i: u32, t: u32, d: u32, ) -> Weight {
		(49_621_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(i as Weight))
			// Standard Error: 34_000
			.saturating_add((43_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_funding_request(i: u32, _t: u32, _d: u32, ) -> Weight {
		(57_819_000 as Weight)
			// Standard Error: 11_000
			.saturating_add((182_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x5f3e4907f716ac89b6347d15ececedcab49a2738eeb30896aacb8b3fb46471bd] (r:1 w:0)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_max_validator_count(t: u32, d: u32, ) -> Weight {
		(55_948_000 as Weight)
			// Standard Error: 88_000
			.saturating_add((51_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 1_000
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_veto_proposal(_t: u32, d: u32, ) -> Weight {
		(55_076_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_create_working_group_lead_opening(i: u32, _t: u32, d: u32, ) -> Weight {
		(51_348_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(i as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_fill_working_group_lead_opening(_t: u32, d: u32, ) -> Weight {
		(51_999_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_update_working_group_budget(t: u32, d: u32, ) -> Weight {
		(44_818_000 as Weight)
			// Standard Error: 310_000
			.saturating_add((179_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 4_000
			.saturating_add((3_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_decrease_working_group_lead_stake(t: u32, d: u32, ) -> Weight {
		(48_434_000 as Weight)
			// Standard Error: 22_000
			.saturating_add((64_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((2_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_slash_working_group_lead(t: u32, d: u32, ) -> Weight {
		(49_434_000 as Weight)
			// Standard Error: 111_000
			.saturating_add((64_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 1_000
			.saturating_add((2_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_working_group_lead_reward(_t: u32, d: u32, ) -> Weight {
		(52_512_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_terminate_working_group_lead(t: u32, d: u32, ) -> Weight {
		(50_486_000 as Weight)
			// Standard Error: 22_000
			.saturating_add((13_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_amend_constitution(i: u32, _t: u32, d: u32, ) -> Weight {
		(52_673_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(i as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_cancel_working_group_lead_opening(_t: u32, d: u32, ) -> Weight {
		(51_512_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_membership_price(_t: u32, d: u32, ) -> Weight {
		(58_153_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_council_budget_increment(_t: u32, d: u32, ) -> Weight {
		(51_512_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_councilor_reward(_t: u32, d: u32, ) -> Weight {
		(51_025_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_initial_invitation_balance(_t: u32, d: u32, ) -> Weight {
		(50_999_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_initial_invitation_count(t: u32, d: u32, ) -> Weight {
		(50_486_000 as Weight)
			// Standard Error: 22_000
			.saturating_add((13_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_membership_lead_invitation_quota(_t: u32, _d: u32, ) -> Weight {
		(53_025_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_set_referral_cut(t: u32, d: u32, ) -> Weight {
		(50_486_000 as Weight)
			// Standard Error: 22_000
			.saturating_add((13_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_create_blog_post(t: u32, _d: u32, h: u32, b: u32, ) -> Weight {
		(65_462_000 as Weight)
			// Standard Error: 22_000
			.saturating_add((38_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(h as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_edit_blog_post(_t: u32, _d: u32, h: u32, b: u32, ) -> Weight {
		(116_289_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(h as Weight))
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_lock_blog_post(t: u32, d: u32, ) -> Weight {
		(49_460_000 as Weight)
			// Standard Error: 155_000
			.saturating_add((38_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 2_000
			.saturating_add((2_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_unlock_blog_post(_t: u32, d: u32, ) -> Weight {
		(52_025_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_update_global_nft_limit(_t: u32, _d: u32, ) -> Weight {
		(52_513_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc13020dc69e85870ac7b4c755bb8753c2] (r:1 w:0)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643ccfbe2f1ab4a3bbc958ab39917ed8b05] (r:1 w:1)
	// Storage: unknown [0x2ce461329fdf4be12bce01afc0af09bc8b18453086fa74ddec96f7b48109d8f4] (r:1 w:0)
	// Storage: unknown [0xc2261276cc9d1f8598ea4b6a74b15c2f218f26c73add634897550b4003b26bc6] (r:1 w:1)
	// Storage: unknown [0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9] (r:1 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f00860d87bd2505058c6624f54d67234bc126] (r:1 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad79596436254e9d55588784fa2a62b726696e2b1] (r:1 w:1)
	// Storage: unknown [0x9a4d7ec4b42d2468c1e2ef6de6dfe59f6d3f46fcaf0e5198d04348f8bb599524] (r:0 w:1)
	// Storage: unknown [0xde7bf41b08da4e09ac0e7c35311f0086dfeb47efcb121b0e718a654f15a6806f] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad795964388c2f7188c6fdd1dffae2fa0d171f440] (r:0 w:1)
	// Storage: unknown [0xf546b188d57525d1826b066ad7959643dae7b75caef993e760989e490027953b] (r:0 w:1)
	fn create_proposal_update_channel_payouts(i: u32, _t: u32, _d: u32, ) -> Weight {
		(57_050_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
}

// Default implementation for tests
impl WeightInfo for () {
	fn create_proposal_signal(i: u32, t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_runtime_upgrade(i: u32, t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_funding_request(i: u32, _t: u32, _d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_max_validator_count(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_veto_proposal(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_create_working_group_lead_opening(i: u32, _t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_fill_working_group_lead_opening(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_update_working_group_budget(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_decrease_working_group_lead_stake(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_slash_working_group_lead(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_working_group_lead_reward(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_terminate_working_group_lead(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_amend_constitution(i: u32, _t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_cancel_working_group_lead_opening(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_membership_price(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_council_budget_increment(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_councilor_reward(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_initial_invitation_balance(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_initial_invitation_count(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_membership_lead_invitation_quota(_t: u32, _d: u32, ) -> Weight {
		0
	}
	fn create_proposal_set_referral_cut(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_create_blog_post(t: u32, _d: u32, h: u32, b: u32, ) -> Weight {
		0
	}
	fn create_proposal_edit_blog_post(_t: u32, _d: u32, h: u32, b: u32, ) -> Weight {
		0
	}
	fn create_proposal_lock_blog_post(t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_unlock_blog_post(_t: u32, d: u32, ) -> Weight {
		0
	}
	fn create_proposal_update_global_nft_limit(_t: u32, _d: u32, ) -> Weight {
		0
	}
	fn create_proposal_update_channel_payouts(i: u32, _t: u32, _d: u32, ) -> Weight {
		0
	}
}
