FROM node:12-alpine

RUN yarn global add typescript
RUN yarn global add ts-node

WORKDIR /home/node

COPY --chown=node:node . .

USER node

RUN yarn install

WORKDIR /home/node/generated/graphql-server
RUN yarn install

WORKDIR /home/node/generated/indexer
RUN yarn install


ENTRYPOINT []
# options: bootstrap, bootstrap:dev, start:dev
CMD ["yarn", "start"]
