// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_election_provider_multi_phase
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-06, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("prod-test"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/joystream-node
// benchmark
// pallet
// --pallet=pallet_election_provider_multi_phase
// --extrinsic=*
// --chain=prod-test
// --steps=50
// --repeat=20
// --execution=wasm
// --template=./scripts/../devops/frame-weight-template.hbs
// --output=./scripts/../runtime/src/weights/pallet_election_provider_multi_phase.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub use pallet_election_provider_multi_phase::weights::WeightInfo;

/// Weights for pallet_election_provider_multi_phase using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Staking CurrentEra (r:1 w:0)
	// Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: Staking CurrentPlannedSession (r:1 w:0)
	// Proof: Staking CurrentPlannedSession (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: Staking ErasStartSessionIndex (r:1 w:0)
	// Proof: Staking ErasStartSessionIndex (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
	// Storage: Babe EpochIndex (r:1 w:0)
	// Proof: Babe EpochIndex (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	// Storage: Babe GenesisSlot (r:1 w:0)
	// Proof: Babe GenesisSlot (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	// Storage: Babe CurrentSlot (r:1 w:0)
	// Proof: Babe CurrentSlot (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	// Storage: Staking ForceEra (r:1 w:0)
	// Proof: Staking ForceEra (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	fn on_initialize_nothing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `845`
		//  Estimated: `14754`
		// Minimum execution time: 22_067 nanoseconds.
		Weight::from_parts(22_863_000, 0u64)
			.saturating_add(Weight::from_parts(0, 14754))
			.saturating_add(T::DbWeight::get().reads(8_u64))
	}
	// Storage: ElectionProviderMultiPhase Round (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	fn on_initialize_open_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3054`
		// Minimum execution time: 14_458 nanoseconds.
		Weight::from_parts(15_139_000, 0u64)
			.saturating_add(Weight::from_parts(0, 3054))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: ElectionProviderMultiPhase Round (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	fn on_initialize_open_unsigned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3054`
		// Minimum execution time: 16_081 nanoseconds.
		Weight::from_parts(16_418_000, 0u64)
			.saturating_add(Weight::from_parts(0, 3054))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: System Account (r:1 w:1)
	// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	// Storage: ElectionProviderMultiPhase QueuedSolution (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase QueuedSolution (max_values: Some(1), max_size: None, mode: Measured)
	fn finalize_signed_phase_accept_solution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `3767`
		// Minimum execution time: 32_558 nanoseconds.
		Weight::from_parts(33_355_000, 0u64)
			.saturating_add(Weight::from_parts(0, 3767))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: System Account (r:1 w:1)
	// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn finalize_signed_phase_reject_solution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `3593`
		// Minimum execution time: 22_260 nanoseconds.
		Weight::from_parts(22_790_000, 0u64)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: ElectionProviderMultiPhase SnapshotMetadata (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SnapshotMetadata (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase DesiredTargets (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase DesiredTargets (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Snapshot (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase Snapshot (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `v` is `[1000, 2000]`.
	/// The range of component `t` is `[500, 1000]`.
	fn create_snapshot_internal(v: u32, _t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 421_232 nanoseconds.
		Weight::from_parts(428_446_000, 0u64)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 2_648
			.saturating_add(Weight::from_parts(206_516, 0u64).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: ElectionProviderMultiPhase SignedSubmissionIndices (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionIndices (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SignedSubmissionNextIndex (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionNextIndex (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SnapshotMetadata (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SnapshotMetadata (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SignedSubmissionsMap (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionsMap (max_values: None, max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase QueuedSolution (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase QueuedSolution (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Round (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase DesiredTargets (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase DesiredTargets (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Snapshot (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase Snapshot (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[500, 800]`.
	/// The range of component `d` is `[200, 400]`.
	fn elect_queued(a: u32, d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `265 + a * (768 ±0) + d * (48 ±0)`
		//  Estimated: `15543 + a * (6912 ±0) + d * (441 ±0)`
		// Minimum execution time: 463_240 nanoseconds.
		Weight::from_parts(97_192_509, 0u64)
			.saturating_add(Weight::from_parts(0, 15543))
			// Standard Error: 7_234
			.saturating_add(Weight::from_parts(671_464, 0u64).saturating_mul(a.into()))
			// Standard Error: 10_844
			.saturating_add(Weight::from_parts(147_107, 0u64).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
			.saturating_add(Weight::from_parts(0, 6912).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 441).saturating_mul(d.into()))
	}
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SnapshotMetadata (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase SnapshotMetadata (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	// Proof: TransactionPayment NextFeeMultiplier (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	// Storage: ElectionProviderMultiPhase SignedSubmissionIndices (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionIndices (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SignedSubmissionNextIndex (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionNextIndex (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SignedSubmissionsMap (r:0 w:1)
	// Proof Skipped: ElectionProviderMultiPhase SignedSubmissionsMap (max_values: None, max_size: None, mode: Measured)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1157`
		//  Estimated: `13226`
		// Minimum execution time: 54_248 nanoseconds.
		Weight::from_parts(56_685_000, 0u64)
			.saturating_add(Weight::from_parts(0, 13226))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Round (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase DesiredTargets (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase DesiredTargets (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase QueuedSolution (r:1 w:1)
	// Proof Skipped: ElectionProviderMultiPhase QueuedSolution (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase SnapshotMetadata (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase SnapshotMetadata (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Snapshot (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Snapshot (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase MinimumUntrustedScore (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase MinimumUntrustedScore (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `v` is `[1000, 2000]`.
	/// The range of component `t` is `[500, 1000]`.
	/// The range of component `a` is `[500, 800]`.
	/// The range of component `d` is `[200, 400]`.
	fn submit_unsigned(v: u32, t: u32, a: u32, _d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147 + v * (553 ±0) + t * (32 ±0)`
		//  Estimated: `11424 + v * (3871 ±0) + t * (224 ±0)`
		// Minimum execution time: 6_346_063 nanoseconds.
		Weight::from_parts(6_428_758_000, 0u64)
			.saturating_add(Weight::from_parts(0, 11424))
			// Standard Error: 18_616
			.saturating_add(Weight::from_parts(234_857, 0u64).saturating_mul(v.into()))
			// Standard Error: 55_166
			.saturating_add(Weight::from_parts(4_846_250, 0u64).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3871).saturating_mul(v.into()))
			.saturating_add(Weight::from_parts(0, 224).saturating_mul(t.into()))
	}
	// Storage: ElectionProviderMultiPhase DesiredTargets (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase DesiredTargets (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Snapshot (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Snapshot (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase Round (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: ElectionProviderMultiPhase MinimumUntrustedScore (r:1 w:0)
	// Proof Skipped: ElectionProviderMultiPhase MinimumUntrustedScore (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `v` is `[1000, 2000]`.
	/// The range of component `t` is `[500, 1000]`.
	/// The range of component `a` is `[500, 800]`.
	/// The range of component `d` is `[200, 400]`.
	fn feasibility_check(v: u32, t: u32, a: u32, _d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `122 + v * (553 ±0) + t * (32 ±0)`
		//  Estimated: `6428 + v * (2212 ±0) + t * (128 ±0)`
		// Minimum execution time: 5_471_441 nanoseconds.
		Weight::from_parts(5_515_262_000, 0u64)
			.saturating_add(Weight::from_parts(0, 6428))
			// Standard Error: 14_947
			.saturating_add(Weight::from_parts(298_330, 0u64).saturating_mul(v.into()))
			// Standard Error: 44_295
			.saturating_add(Weight::from_parts(3_781_459, 0u64).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(Weight::from_parts(0, 2212).saturating_mul(v.into()))
			.saturating_add(Weight::from_parts(0, 128).saturating_mul(t.into()))
	}
}
